version: '3.8'

services:
  app:
    build: .
    container_name: sistema-provas
    restart: always
    ports:
      - "2502:2502"
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
      - SESSION_SECRET=${SESSION_SECRET}
      - PORT=2502
